INSERT INTO clientes (id, nombre, apellido,forma_pago, creado_en, editado_en) VALUES (1,'Alex','collado','debito',NULL,NULL),(2,'Andres','Guzman','credito',NULL,NULL),(3,'Pepe','don','paypal',NULL,NULL),(4,'Mario','Bros','credito',NULL,NULL),(6,'Julio','Rodriguez','credito',NULL,NULL),(7,'Jose','Perez','paypal',NULL,NULL),(8,'Lucy','Martinez','paypal',NULL,NULL),(9,'Luna','Garcia','credito',NULL,NULL),(10,'Maria','Mena','paypal',NULL,NULL),(13,'Andres','Guzman','debito',NULL,NULL),(14,'luz','german','credito',NULL,NULL),(15,'Pedro','marios','debito','2023-06-17 23:24:11','2023-06-17 23:24:57'),(16,'carlito','diaz','debito','2023-06-17 23:30:37','2023-06-18 13:20:08');
INSERT INTO alumnos(id, nombre, apellido) VALUES(1, 'Johana', 'Doe');
INSERT INTO alumnos(id, nombre, apellido) VALUES(2, 'Pepe', 'Gon');
INSERT INTO cursos(id, titulo, profesor) VALUES(1, 'Curso Spring', 'Andres');
INSERT INTO cursos(id, titulo, profesor) VALUES(2, 'Curso JavaEE 9', 'Andres');
INSERT INTO direcciones(calle, numero) VALUES ('vaticano', 123);
INSERT INTO direcciones(calle, numero) VALUES ('colon', 456);
INSERT INTO tbl_clientes_direcciones(id_cliente, id_direccion) VALUES(1, 1);
INSERT INTO tbl_clientes_direcciones(id_cliente, id_direccion) VALUES(1, 2);
INSERT INTO clientes_detalles (prime, puntos_acumulados, cliente_detalle_id) VALUES (1, 8000, 1);
INSERT INTO tbl_alumnos_cursos(alumno_id, curso_id) VALUES(1, 1);
INSERT INTO tbl_alumnos_cursos(alumno_id, curso_id) VALUES(1, 2);
INSERT INTO facturas(descripcion, total, id_cliente) VALUES('oficina', 4000, 1);
INSERT INTO facturas(descripcion, total, id_cliente) VALUES('casa', 2000, 1);
INSERT INTO facturas(descripcion, total, id_cliente) VALUES('deporte', 3000, 1);
INSERT INTO facturas(descripcion, total, id_cliente) VALUES('computacion', 7000, 1);